import os
os.system("sudo apt install python3-pip --yes") 
os.system("sudo apt-get install python3-tk --yes") 
os.system("pip install pyqt5 pyqt5-tools --yes") 
os.system("sudo apt install libgl1-mesa-glx --yes")
os.system("sudo apt install libegl1-mesa libxkbcommon-x11-0 --yes")
os.system("sudo apt install libxcb-xinerama0 libxcb1 libxcb-util1 libx11-xcb1 libxrender1 libxi6 --yes")
os.system("sudo apt install qt5-default --yes")
os.system("sudo apt install qtbase5-dev qtbase5-dev-tools --yes")
os.system("sudo apt install libxkbcommon-x11-0 --yes")
os.system("sudo apt install qt5-qpa-plugins --yes")
os.system("pip install requests --yes")
os.system("pip install flask --yes")